index = "idx"
prefix = "."
stop-words = "stopwords.txt"
corpus = "line.toml"
dataset = "data"
[ranker]
	k3 = 500
	k1 = 1.20000
	b = 0.750000
	method = "bm25"
[[analyzers]]
	ngram = 1
	method = "ngram-word"
	[[analyzers.filter]]
		type = "icu-tokenizer"
	[[analyzers.filter]]
		type = "lowercase"
